//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendeeDetail
    {
        public int AttendeeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> WebinarID { get; set; }
        public string Attended { get; set; }
        public Nullable<int> InterestRating { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> RegistrationDateTime { get; set; }
        public string JoinTimeLeaveTimeTimeinSession { get; set; }
        public string TimeinSession { get; set; }
        public string Unsubscribed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
    }
}
