//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using EPAM.RDPreEducationPortal.Web.Site.Models;
    using System;
    using System.Collections.Generic;

    public partial class Candidate_Details : CandidateDetails
    {
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> CandidateLocationID { get; set; }
        public string CandidateEmail { get; set; }
        public string ContactNumber { get; set; }
        public string CandidateResume { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> StartingTime { get; set; }
        public Nullable<int> PreviousAssessments { get; set; }
        public string Duration { get; set; }
        public Nullable<double> MarksScored { get; set; }
        public Nullable<bool> Result { get; set; }
        public string Report { get; set; }
        public string PublicReport { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNumber { get; set; }
        public string GraduationCollegeName { get; set; }
        public string Graduation { get; set; }
        public string GraduationSpecialty { get; set; }
        public Nullable<int> YearOfPassedOut { get; set; }
        public string GraduationMarksCGPA { get; set; }
        public string C12MarksCGPA { get; set; }
        public string C10MarksCGPA { get; set; }
        public string Gender { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentStateOfResidence { get; set; }
        public string CurrentAddress { get; set; }
        public string GovernmentIssuedIDProof { get; set; }
        public string PreferredJobLocation { get; set; }
        public Nullable<int> RecruitmentId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string SecondRoundPublicReport { get; set; }
        public Nullable<bool> IsPEPStudent { get; set; }
        public Nullable<bool> IsCodathonWinner { get; set; }
        public Nullable<bool> IsGDCleared { get; set; }
        public string GDComments { get; set; }
        public string PreferredLocationForSecondRound { get; set; }
    }
}
