//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Marks
    {
        public int MarksID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<double> MCQs { get; set; }
        public Nullable<double> CodingChallenge1 { get; set; }
        public Nullable<double> CodingChallenge2 { get; set; }
        public Nullable<double> CodingChallenge3 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public string MarksScored { get; set; }
        public string Result { get; set; }
        public string RoundType { get; set; }
    }
}
