//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using EPAM.RDPreEducationPortal.Web.Site.Models;
    using System;
    using System.Collections.Generic;

    public partial class HRAssessment : BaseClass
    {
        public int HRAssessmentID { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PresentationSkills { get; set; }
        public Nullable<int> ProfessionalImpression { get; set; }
        public Nullable<int> SelfManagement { get; set; }
        public Nullable<int> CommunicationInterpersonalSkills { get; set; }
        public Nullable<int> StressTolerance { get; set; }
        public Nullable<int> DecisionMaking { get; set; }
        public Nullable<int> Learnability { get; set; }
        public Nullable<int> OrganizationalFit { get; set; }
        public Nullable<int> Creative { get; set; }
        public Nullable<int> Expert { get; set; }
        public Nullable<int> Original { get; set; }
        public Nullable<int> Candid { get; set; }
        public Nullable<int> Intelligent { get; set; }
        public Nullable<int> Driven { get; set; }
        public Nullable<int> ValueTheIndividual { get; set; }
        public Nullable<int> FocusOnCustomer { get; set; }
        public Nullable<int> ActAsATeam { get; set; }
        public Nullable<int> StriveForExcellence { get; set; }
        public Nullable<int> ActWithIntegrity { get; set; }
        public Nullable<int> Humble { get; set; }
        public Nullable<int> Hungry { get; set; }
        public Nullable<int> Smart { get; set; }
        public string SignificantAchievements { get; set; }
        public string PlansForFurtherStudies { get; set; }
        public string CareerPlans { get; set; }
        public Nullable<int> OverallRating { get; set; }
        public string OverallComments { get; set; }
        public Nullable<bool> Recommendation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public Nullable<bool> HighlyRecommended { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
    }
}
