//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment_Rounds
    {
        public int RoundID { get; set; }
        public string RoundName { get; set; }
        public string RoundKey { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
