//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_GitRepositories
    {
        public int GitRepositoryID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string RepositoryUrl { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Comments { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
    }
}
