//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using EPAM.RDPreEducationPortal.Web.Site.Models;
    using System;
    using System.Collections.Generic;

    public partial class TechnicalAssessment : BaseClass
    {
        public int TechnicalAssessmentID { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Section1Rating { get; set; }
        public string Section1Remarks { get; set; }
        public Nullable<int> Section2Rating { get; set; }
        public string Section2Remarks { get; set; }
        public Nullable<int> Section3Rating { get; set; }
        public string Section3Remarks { get; set; }
        public Nullable<int> Section4Rating { get; set; }
        public string Section4Remarks { get; set; }
        public Nullable<int> Section5Rating { get; set; }
        public string Section5Remarks { get; set; }
        public Nullable<int> EPAMFit { get; set; }
        public string OverallRemarks { get; set; }
        public Nullable<int> OverallRating { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public string AdditionalRemarks { get; set; }
        public Nullable<int> AdditionalRating { get; set; }
        public Nullable<bool> HighlyRecommended { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
    }
}
