//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using EPAM.RDPreEducationPortal.Web.Site.Models;
    using System;
    using System.Collections.Generic;

    public partial class User : BaseClass
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public Nullable<int> MarksScored { get; set; }
        public string GraduationSpecialty { get; set; }
        public string EmailAddressToSendNotifications { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
    }
}
