//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.RDPreEducationPortal.Web.Site.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webinar
    {
        public int WebinarID { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Registered { get; set; }
        public Nullable<int> Attended { get; set; }
        public Nullable<int> ClickedRegistrationLink { get; set; }
        public Nullable<int> OpenedInvitation { get; set; }
    }
}
